name: CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install pytest-cov
        pip install git+https://github.com/deepmind/dm-haiku
        python -m pip install flax
        pip install -e .
    - name: Test coverage.
      run: |
        pytest --cov emlp --cov-report xml:cov.xml tests/*.py
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        files: ./cov.xml
        name: codecov-umbrella
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true